---
- name: Consultar info de todos los dominios de un tenant de ACI
  hosts: localhost

  tasks:
    - name: Query all tenants
      cisco.aci.aci_domain:
        host: 10.54.100.243
        username: admin
        password: cisco123
        domain_type: phys  
        state: query
        validate_certs: no
      register: tenant_response

    - name: Mostrar información del Tenant
      debug:
        var: tenant_response
